name: 'Black Box Tests'
on:
    push:
        branches:
            - release/**
        tags:
            - v4.*

jobs:
    build:
        strategy:
            matrix:
                node: [18]
        name: Build Packages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
            - run: yarn
            - run: tar -czf /tmp/web3-${{ matrix.node }}.js.tar.gz --exclude="./.git" ./
            - uses: actions/upload-artifact@v4
              with:
                  name: web3-${{ matrix.node }}.js.tar.gz
                  path: /tmp/web3-${{ matrix.node }}.js.tar.gz
    black-box:
        name: Black Box
        needs: build
        runs-on: ubuntu-latest
        env:
            INFURA_MAINNET_HTTP: ${{ secrets.INFURA_MAINNET_HTTP }}
            INFURA_MAINNET_WS: ${{ secrets.INFURA_MAINNET_WS }}
            INFURA_SEPOLIA_WS: ${{ secrets.INFURA_SEPOLIA_WS }}
            MODE: ${{ matrix.mode }}
        strategy:
            fail-fast: false
            matrix:
                node: [18]
                mode: ['http', 'ws']
                backend: ['geth', 'infura']
        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
            - uses: actions/download-artifact@v4
              with:
                  name: web3-${{ matrix.node }}.js.tar.gz
                  path: /tmp
            - run: tar -xf /tmp/web3-${{ matrix.node }}.js.tar.gz -C ./
            - run: |
                  yarn test:blackbox:${{ matrix.backend }}:${{ matrix.mode }}
              shell: bash
